name: http_mock_adapter
description: A simple to use mocking package for Dio intended to be used in tests. It provides various types and methods to declaratively mock request-response communication.
version: 0.4.4
homepage: https://github.com/lomsa-dev/http-mock-adapter
repository: https://github.com/lomsa-dev/http-mock-adapter
issue_tracker: https://github.com/lomsa-dev/http-mock-adapter/issues

environment:
  sdk: '>=2.18.3 <3.0.0'

dependencies:
  collection: ^1.17.1
  dio: ^5.2.1
  http_parser: ^4.0.2

dev_dependencies:
  lints: '>=1.0.1'
  test: ^1.24.3
  fake_async: ^1.3.1
