name: http_mock_adapter
description: HTTP mock adapter for Dio & Mockito. By simply defining requests and corresponding responses through predefined adapters, you will be able to mock requests sent via Dio.
version: 0.1.0
homepage: https://lomsa.com
repository: https://github.com/lomsa-dev/http-mock-adapter
issue_tracker: https://github.com/lomsa-dev/http-mock-adapter/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  meta: ^1.2.3
  mockito: ^4.1.3

dev_dependencies:
  pedantic: ^1.9.0
  http: ^0.12.2
  test: any
